# Language dependent settings:
# Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory

[en]
title = "GitHub Certified"
weight = 1
languageCode = 'en-US'
languageName = 'English'
contentDir = 'content/en'

[en.params]
editURL = 'https://github.com/FidelusAleksander/ghcertified/edit/master/content/en/'

[pt]
title = "GitHub Certified"
weight = 2
languageCode = 'pt-BR'
languageName = 'Português'
contentDir = 'content/pt'

[pt.params]
editURL = 'https://github.com/FidelusAleksander/ghcertified/edit/master/content/pt/'

[pl]
title = "GitHub Certified"
weight = 3
languageCode = 'pl-PL'
languageName = 'Polski'
contentDir = 'content/pl'

[pl.params]
editURL = 'https://github.com/FidelusAleksander/ghcertified/edit/master/content/pl/'

[es]
title = "GitHub Certified"
weight = 4
languageCode = 'es-ES'
languageName = 'Español'
contentDir = 'content/es'

[es.params]
editURL = 'https://github.com/FidelusAleksander/ghcertified/edit/master/content/es/'

[ja]
title = "GitHub Certified"
weight = 4
languageCode = 'ja-JP'
languageName = 'Japanese'
contentDir = 'content/ja'

[ja.params]
editURL = 'https://github.com/FidelusAleksander/ghcertified/edit/master/content/ja/'