# Language dependent settings:
# Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory

[en]
title = "GitHub Certified"
weight = 1
languageCode = 'en-US'
languageName = 'English'
contentDir = 'content/en'
