version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 1
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 14
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/app'
    open-pull-requests-limit: 1
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 14
    groups:
      npm-dependencies:
        patterns:
          - '*'
