content:
- changed-files:
  - any-glob-to-any-file: "content/**/*"

actions:
- changed-files:
  - any-glob-to-any-file: "content/questions/actions/*"

admin:
- changed-files:
  - any-glob-to-any-file: "content/questions/admin/*"

advanced security:
- changed-files:
  - any-glob-to-any-file: "content/questions/advanced_security/*"

foundations:
- changed-files:
  - any-glob-to-any-file: "content/questions/foundations/*"

documentation:
- changed-files:
  - any-glob-to-any-file: ["README.md", "CONTRIBUTING.md"]

dependencies:
- changed-files:
  - any-glob-to-any-file: "themes/**/*"
- head-branch: ['dependabot/*']
