content:
- changed-files:
  - any-glob-to-any-file: "questions/**/*"

actions:
- changed-files:
  - any-glob-to-any-file: "questions/en/actions/*"

admin:
- changed-files:
  - any-glob-to-any-file: "questions/en/admin/*"

advanced security:
- changed-files:
  - any-glob-to-any-file: "questions/en/advanced_security/*"

foundations:
- changed-files:
  - any-glob-to-any-file: "questions/en/foundations/*"

copilot:
- changed-files:
  - any-glob-to-any-file: "questions/en/copilot/*"

translations:
- changed-files:
  - any-glob-to-any-file:
    - "questions/es/**"
    - "questions/pt/**"
    - "questions/pl/**"
    - "questions/ja/**"
    - "app/messages/es.json"
    - "app/messages/pt.json"
    - "app/messages/pl.json"
    - "app/messages/ja.json"

documentation:
- changed-files:
  - any-glob-to-any-file: ["README.md", "CONTRIBUTING.md"]

dependencies:
- changed-files:
  - any-glob-to-any-file: ["**/package.json", "**/package-lock.json"]
