languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Github Actions Quiz"
baseUrl                  = "https://fidelusaleksander.github.io/github-actions-quiz/"

description = "Github Actions certification preparation quiz"


theme = "hugo-theme-learn"

[params]
  description = "A Custom Hugo Shortcode for Interactive Quizzes"
  author = "Malte Bonart"
  showVisitedLinks = false
  disableBreadcrumb = true
  disableNextPrev = true
  disableSearch = true
  disableHistory= true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[minify]
  disableHTML = true

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/FidelusAleksander/github-actions-quiz"
weight = 10
