name: Add comment to new issue
on:
  issues:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueComment = `
              Hello @${{ github.event.issue.user.login }} :wave:,

              Please note that the core maintainer of this repository will not be available for support or any work on this repo for the upcoming months. As a result, new features will not be added during this period. Only additions or updates of new questions or study resources will be accepted. 
  
              We encourage you to follow the [CONTRIBUTING](https://github.com/FidelusAleksander/ghcertified/blob/master/CONTRIBUTING.md) guide and raise pull requests with fixes for content issues you find. Content pull requests will be reviewed by another maintainer.
  
              Thank you for your understanding and contribution! :rocket:
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
