name: Preview Build

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  build:
    name: Build Next.js Site
    if: github.event.label.name == 'request-preview-deployment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: cd app && npm ci

      - name: Build site
        run: cd app && npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: nextjs-build
          path: app/out/
          retention-days: 1

