name: Translate a File

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      language_code:
        required: true
        type: string
      language_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      file:
        description: 'File path to translate (e.g., content/en/questions/foundations/example.md)'
        required: true
        type: string
        default: 'content/en/questions/actions/question-029.md'
      language_code:
        description: 'Target language code (e.g., pl, pt)'
        required: true
        type: string
        default: 'pl'
      language_name:
        description: 'Target language name (e.g., Polish, Portuguese)'
        required: true
        type: string
        default: 'Polish'

jobs:
  translate:
    name: Translate ${{ inputs.file}} to ${{ inputs.language_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build System Prompt
        id: build-system-prompt
        uses: skills/action-text-variables@v3
        with:
          template-file: .github/translation-system-prompt.md
          template-vars: |
            targetLanguage: ${{ inputs.language_name }}

      - name: Translate file
        uses: FidelusAleksander/prompt-action@v1
        id: translate
        with:
          system-prompt: ${{ steps.build-system-prompt.outputs.updated-text }}
          prompt-file: ${{ inputs.file }}

      - name: Save translation
        id: save-translation
        run: |
          FILE="${{ inputs.file }}"
          LANG="${{ inputs.language_code }}"

          TARGET_PATH="${FILE/content\/en/content\/$LANG}"
          TARGET_DIR=$(dirname "$TARGET_PATH")

          mkdir -p "$TARGET_DIR"
          echo "$TRANSLATED_TEXT" > "$TARGET_PATH"
        env:
          TRANSLATED_TEXT: ${{ steps.translate.outputs.response }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "content/${{ inputs.language_code }}/**"
          message: "i18n: translate ${{ inputs.file }} to ${{ inputs.language_name }}"
          push: true
          new_branch: i18n/update-translations
