name: Translate a File

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      language_code:
        required: true
        type: string
      language_name:
        required: true
        type: string

jobs:
  translate:
    name: Translate ${{ inputs.file}} to ${{ inputs.language_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Translate file
        uses: actions/ai-inference@v1.1.0
        id: translate
        with:
          prompt-file: ${{ inputs.file }}
          system-prompt: |
            You are a highly skilled ${{ inputs.language_name }} translator.
            Your responsibilities:
            - Translate the provided text to ${{ inputs.language_name }}
            - Preserve the meaning, tone, formatting and style of the original text
            - Detect the source language automatically
            - Return only the translation, no explanations or notes

              Keep technical terms, GitHub nomenclature, code blocks, and Front Matter
              in their original form. Maintain Markdown formatting.

              For consistency, use the following glossary of technical terms, if a term appears in the glossary, always use the provided translation.:
              ${{ secrets.PT_GLOSSARY }}

      - name: Save translation
        id: save-translation
        run: |
          FILE="${{ inputs.file }}"
          LANG="${{ inputs.language_code }}"

          TARGET_PATH="${FILE/content\/en/content\/$LANG}"
          TARGET_DIR=$(dirname "$TARGET_PATH")

          mkdir -p "$TARGET_DIR"
          echo "$TRANSLATED_TEXT" > "$TARGET_PATH"
        env:
          TRANSLATED_TEXT: ${{ steps.translate.outputs.response }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "content/${{ inputs.language_code }}/**"
          message: "i18n: translate ${{ inputs.file }} to ${{ inputs.language_name }}"
          push: true
          new_branch: i18n/update-translations
