name: Translate Content Files

on:
  push:
    branches:
      - master
    paths:
      - "content/en/**"

permissions:
  contents: write
  pull-requests: write
  models: read

jobs:
  detect-changes:
    name: Build Matrix of Changed Files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          files: |
            content/en/**

  translate:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_files != ''
    strategy:
      max-parallel: 1
      matrix:
        language:
          # [{ code: "pt", name: "Portuguese" }, { code: "pl", name: "Polish" }]
          [{ code: "pl", name: "Polish" }]

        file: ${{ fromJSON(needs.detect-changes.outputs.changed_files) }}
    uses: ./.github/workflows/translate-file.yml
    with:
      file: ${{ matrix.file }}
      language_code: ${{ matrix.language.code }}
      language_name: ${{ matrix.language.name }}

  create-pr:
    needs: translate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "i18n: update translations of changed content" \
            --body "This PR updates translations for recently changed content." \
            --base master \
            --head i18n/update-translations
